//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// MFCBitOverlapSample.rc で使用
//
#define IDD_MFC_BITOVERLAPSAMPLE_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDS_STRING_DATA_TYPE_TABLE_COL_TITLE_NO 130
#define IDS_STRING_DATA_TYPE_TABLE_COL_TITLE_DATA_TYPE 131
#define IDD_MFC_INPUT_NEW_DATA_TYPE_DIALOG 131
#define IDS_STRING_DATA_TYPE_TABLE_COL_TITLE_NAME 132
#define IDS_STRING_DATA_TYPE_TABLE_COL_TITLE_OFFSET 133
#define IDS_STRING_DATA_TYPE_TABLE_COL_TITLE_REMARKS 134
#define IDC_BUTTON_RUN_CHECK            1000
#define IDC_LIST2                       1002
#define IDC_BUTTON_ADD_ITEM             1003
#define IDC_BUTTON_DELETE_ITEM          1004
#define IDC_COMBO_DATA_TYPE             1004
#define IDC_BUTTON_CHECK_ITEM           1005
#define IDC_EDIT_DATA_OFFSET            1005
#define IDC_BUTTON_EXPORT_DATA          1006
#define IDC_EDIT_DATA_NAME              1007
#define IDC_BUTTON_EDIT_DATA            1007
#define IDC_EDIT_DATA_REMARK            1008
#define IDC_BUTTON_OK                   1009
#define IDC_BUTTON_CANCEL               1010
#define IDS_STRING_ERROR_WHILE_INIT     10000
#define IDS_STRING_ERROR_WHILE_LOAD_STRING_TABLE 10001
#define IDS_STRING_ERROR_DEL_NO_ROW_SELECTED2 10002
#define IDS_STRING_ERROR_DEL_NO_ROW_SELECTED 10002
#define IDS_STRING_ERROR_EDIT_NO_ROW_SELECTED 10003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
